DROP TABLE PRODUCTS;
DROP TABLE PRODUCT_CATEGORIES;

CREATE TABLE PRODUCT_CATEGORIES
(
    "CATEGORY" VARCHAR(50) PRIMARY KEY,
    "ARCHIVED" BOOLEAN
);

CREATE TABLE PRODUCTS
(
    "ID"          INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "CATEGORY"    VARCHAR(50) REFERENCES PRODUCT_CATEGORIES (CATEGORY) ON DELETE CASCADE,
    "NAME"        VARCHAR(50),
    "DESCRIPTION" LONG VARCHAR,
    "STOCK"       INTEGER,
    "PRICE"       DOUBLE,
    "ARCHIVED"    BOOLEAN
);
