DROP TABLE ORDERS;
DROP TABLE ORDER_LINE;

CREATE TABLE ORDERS
(
    "ID"               INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "CUSTOMER_ID"      INTEGER REFERENCES CUSTOMERS (ID) ON DELETE CASCADE,
    "ORDERED_ON"       TIMESTAMP,
    "SHIPPING_ADDRESS" VARCHAR(255),
    "TOTAL"            DOUBLE,
    "STATUS"           VARCHAR(30),
    "TRACKING_ID"      VARCHAR(30),
    "CARD_USED"        VARCHAR(20)
);

CREATE TABLE ORDER_LINE
(
    "ORDER_ID"         INTEGER REFERENCES ORDERS (ID) ON DELETE CASCADE,
    "PRODUCT_ID"       INTEGER REFERENCES PRODUCTS (ID) ON DELETE CASCADE,
    "QUANTITY_ORDERED" INTEGER,
    "PRICE"            DOUBLE,
    PRIMARY KEY (ORDER_ID, PRODUCT_ID)
);
